version: '2'

services:

  # Minio container#
  minio:
      container_name: minio
      image: rpi-minio
      restart: always
      ports:
         - 9000:9000
      environment:
          - MINIO_ACCESS_KEY=nibz78
          - MINIO_SECRET_KEY=?Nitram78250
      volumes:
          - miniodata:/data
volumes:
   miniodata:
     external: true
